/**
 * RED-first unit tests for the hand-written `ListEntries` proto3 wire codec (slice P2R-PV-S3b).
 *
 * These run with NO kernel and NO network: they assert the encode/decode codecs the grpc-js client
 * uses are byte-correct against a KNOWN wire fixture, mirroring the Append codec the R2-S6 transport
 * tests lock. The decoder MUST reconstruct every Entry field (sequence / canonical_event / prev_hash /
 * entry_hash) from the proto3 bytes — a dropped or mis-tagged field is a RED test.
 *
 * Wire layout (ingest.proto, regenerated by S3a):
 *   ListEntriesRequest { from_sequence = 1 : uint64 (varint) }
 *   ListEntriesResponse { repeated Entry = 1 (len-delimited) }
 *   Entry { sequence = 1 : uint64, canonical_event = 2 : bytes, prev_hash = 3 : string,
 *           entry_hash = 4 : string }
 */
import { describe, expect, it } from "vitest";
import type { Entry } from "../_generated/ingest/ingest.js";
import { decodeListEntriesResponse, encodeListEntriesRequest } from "./grpc-client.js";

// --- a tiny, independent proto3 encoder used ONLY to build a known fixture (not the production path) ---

function pushVarint(out: number[], value: number): void {
  let v = value;
  while (v > 0x7f) {
    out.push((v & 0x7f) | 0x80);
    v = Math.floor(v / 128);
  }
  out.push(v & 0x7f);
}

function pushTag(out: number[], field: number, wireType: number): void {
  pushVarint(out, field * 8 + wireType);
}

function pushLenDelim(out: number[], field: number, bytes: Uint8Array): void {
  pushTag(out, field, 2);
  pushVarint(out, bytes.length);
  for (const b of bytes) out.push(b);
}

function pushString(out: number[], field: number, value: string): void {
  pushLenDelim(out, field, new TextEncoder().encode(value));
}

/** Encode one Entry to its proto3 message bytes (sequence/canonical_event/prev_hash/entry_hash). */
function encodeEntry(e: Entry): Uint8Array {
  const out: number[] = [];
  if (e.sequence !== 0) {
    pushTag(out, 1, 0);
    pushVarint(out, e.sequence);
  }
  if (e.canonicalEvent.length > 0) pushLenDelim(out, 2, e.canonicalEvent);
  if (e.prevHash.length > 0) pushString(out, 3, e.prevHash);
  if (e.entryHash.length > 0) pushString(out, 4, e.entryHash);
  return Uint8Array.from(out);
}

/** Encode a ListEntriesResponse: repeated Entry (field 1, len-delimited). */
function encodeListEntriesResponseFixture(entries: readonly Entry[]): Buffer {
  const out: number[] = [];
  for (const e of entries) pushLenDelim(out, 1, encodeEntry(e));
  return Buffer.from(out);
}

describe("ListEntries request encoder (S3b)", () => {
  it("encodes from_sequence as a field-1 varint; omits the proto3 zero value", () => {
    // partitionId: "" is the single-chain (Personal) default — the hand-written encoder omits it on
    // the wire (proto3 default), so only from_sequence is emitted (PK1 leaves the single-chain wire
    // byte-identical).
    const withFrom = encodeListEntriesRequest({ fromSequence: 1, partitionId: "" });
    // tag = field 1, wiretype 0 (varint) => 0x08 ; value 1 => 0x01
    expect(Array.from(withFrom)).toEqual([0x08, 0x01]);

    const zero = encodeListEntriesRequest({ fromSequence: 0, partitionId: "" });
    // proto3 zero value is omitted on the wire.
    expect(zero.length).toBe(0);
  });
});

describe("ListEntries response decoder (S3b)", () => {
  it("decodes every Entry field (sequence / canonical_event / prev_hash / entry_hash) round-trip", () => {
    const canonical0 = new TextEncoder().encode('{"a":1}');
    const canonical1 = new TextEncoder().encode('{"b":2}');
    const fixture: Entry[] = [
      {
        sequence: 0,
        canonicalEvent: canonical0,
        prevHash: `sha256:${"0".repeat(64)}`,
        entryHash: `sha256:${"a".repeat(64)}`,
      },
      {
        sequence: 1,
        canonicalEvent: canonical1,
        prevHash: `sha256:${"a".repeat(64)}`,
        entryHash: `sha256:${"b".repeat(64)}`,
      },
    ];

    const bytes = encodeListEntriesResponseFixture(fixture);
    const decoded = decodeListEntriesResponse(bytes);

    expect(decoded.entries.length).toBe(2);
    const [e0, e1] = decoded.entries;
    expect(e0?.sequence).toBe(0);
    expect(Array.from(e0?.canonicalEvent ?? new Uint8Array())).toEqual(Array.from(canonical0));
    expect(e0?.prevHash).toBe(`sha256:${"0".repeat(64)}`);
    expect(e0?.entryHash).toBe(`sha256:${"a".repeat(64)}`);
    expect(e1?.sequence).toBe(1);
    expect(Array.from(e1?.canonicalEvent ?? new Uint8Array())).toEqual(Array.from(canonical1));
    expect(e1?.prevHash).toBe(`sha256:${"a".repeat(64)}`);
    expect(e1?.entryHash).toBe(`sha256:${"b".repeat(64)}`);
  });

  it("decodes an empty response to an empty entries array", () => {
    const decoded = decodeListEntriesResponse(Buffer.from([]));
    expect(decoded.entries).toEqual([]);
  });
});
