// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.28.1
// source: agt_decision.subset.proto

/* eslint-disable */

export const protobufPackage = "agentos.agt.decision.v1";

export interface GovernanceProjection {
  /** Pins the projection contract version (src/policy/governance-projection.ts: version = 1). */
  version: number;
  /** Coarse class derived from basename(argv0): filesystem / network / shell / process / unknown. */
  operationClass: string;
  /** argv[0], redacted. */
  argv0: string;
  /** Original token count (BEFORE truncation) — truncation is explicit, never silent. */
  argc: number;
  /** Each token redactSecrets'd, bounded at MAX_TOKENS. */
  argvRedacted: string[];
  /** True when argc > MAX_TOKENS (the overflow that argv_redacted dropped). */
  truncated: boolean;
  /** basename(argv0) is a known shell AND some later token is exactly `-c`. */
  usesShellInterpreter: boolean;
  /** host[:port] extracted from URL-like / host:port tokens; userinfo stripped, redacted, de-duped. */
  networkHosts: string[];
  /** Best-effort intersection with a known destructive-flag set — a HINT for AGT, not exhaustive. */
  destructiveFlags: string[];
}

export interface AgtEvaluateRequest {
  requestId: string;
  tenantId: string;
  projectId: string;
  taskId: string;
  actorId: string;
  action: string;
  resource: string;
  /**
   * The credential-blind R9b-1 projection (optional: absent => the sidecar evaluates on neutral
   * fields alone). NEVER raw args.
   */
  governanceProjection: GovernanceProjection | undefined;
}

export interface AgtEvaluateResponse {
  allowed: boolean;
  action: string;
  matchedRule: string;
  reason: string;
}

export interface AgtDecision {
  /**
   * Evaluate one governed tool-call. The transport sends neutral governance fields + the
   * credential-blind GovernanceProjection; the sidecar returns an advisory decision. Only an
   * unambiguous { allowed:true, action:"allow" } maps to allow on our side — everything else
   * (deny/warn/log/require_approval/unknown/malformed) is fail-closed to a deny.
   */
  Evaluate(request: AgtEvaluateRequest): Promise<AgtEvaluateResponse>;
}
