// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: ingest.proto

package ingestpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppendService_Append_FullMethodName      = "/agentos.kernel.ingest.v1.AppendService/Append"
	AppendService_Checkpoint_FullMethodName  = "/agentos.kernel.ingest.v1.AppendService/Checkpoint"
	AppendService_ListEntries_FullMethodName = "/agentos.kernel.ingest.v1.AppendService/ListEntries"
)

// AppendServiceClient is the client API for AppendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AppendService is the kernel's ingest surface. It is APPEND-ONLY by construction: exactly one RPC
// (Append) and no Update/Delete/Rewrite/Upsert/Overwrite — the control plane can only append, never
// rewrite history (HARD CONSTRAINT; gating c1/c4). The server additionally enforces monotonic
// per-source sequence and fails closed (typed AppendError + audit) on replay/gap/malformed.
type AppendServiceClient interface {
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	// Checkpoint is READ-ONLY: under the same append mutex it atomically captures a consistent snapshot
	// anchor {head_entry_hash, head_sequence, per_source_next_seq}. It NEVER appends, rewrites, or
	// truncates — it is a consistent read of the chain head + per-source next sequence so a snapshot
	// cannot observe a torn (half-written) tail. It does NOT widen the append-only surface.
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	// ListEntries is READ-ONLY: under the same append mutex it captures a consistent snapshot of the
	// durable WORM chain (store.Load), filters to sequence >= from_sequence, and returns the entries so a
	// client can re-derive entryHash and verify chain integrity (reading != attesting). It NEVER appends,
	// rewrites, or truncates, and on a durable read failure returns Internal — never a partial slice. It
	// does NOT widen the append-only surface.
	ListEntries(ctx context.Context, in *ListEntriesRequest, opts ...grpc.CallOption) (*ListEntriesResponse, error)
}

type appendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppendServiceClient(cc grpc.ClientConnInterface) AppendServiceClient {
	return &appendServiceClient{cc}
}

func (c *appendServiceClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, AppendService_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appendServiceClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, AppendService_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appendServiceClient) ListEntries(ctx context.Context, in *ListEntriesRequest, opts ...grpc.CallOption) (*ListEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEntriesResponse)
	err := c.cc.Invoke(ctx, AppendService_ListEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppendServiceServer is the server API for AppendService service.
// All implementations must embed UnimplementedAppendServiceServer
// for forward compatibility.
//
// AppendService is the kernel's ingest surface. It is APPEND-ONLY by construction: exactly one RPC
// (Append) and no Update/Delete/Rewrite/Upsert/Overwrite — the control plane can only append, never
// rewrite history (HARD CONSTRAINT; gating c1/c4). The server additionally enforces monotonic
// per-source sequence and fails closed (typed AppendError + audit) on replay/gap/malformed.
type AppendServiceServer interface {
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	// Checkpoint is READ-ONLY: under the same append mutex it atomically captures a consistent snapshot
	// anchor {head_entry_hash, head_sequence, per_source_next_seq}. It NEVER appends, rewrites, or
	// truncates — it is a consistent read of the chain head + per-source next sequence so a snapshot
	// cannot observe a torn (half-written) tail. It does NOT widen the append-only surface.
	Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	// ListEntries is READ-ONLY: under the same append mutex it captures a consistent snapshot of the
	// durable WORM chain (store.Load), filters to sequence >= from_sequence, and returns the entries so a
	// client can re-derive entryHash and verify chain integrity (reading != attesting). It NEVER appends,
	// rewrites, or truncates, and on a durable read failure returns Internal — never a partial slice. It
	// does NOT widen the append-only surface.
	ListEntries(context.Context, *ListEntriesRequest) (*ListEntriesResponse, error)
	mustEmbedUnimplementedAppendServiceServer()
}

// UnimplementedAppendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppendServiceServer struct{}

func (UnimplementedAppendServiceServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedAppendServiceServer) Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedAppendServiceServer) ListEntries(context.Context, *ListEntriesRequest) (*ListEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEntries not implemented")
}
func (UnimplementedAppendServiceServer) mustEmbedUnimplementedAppendServiceServer() {}
func (UnimplementedAppendServiceServer) testEmbeddedByValue()                       {}

// UnsafeAppendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppendServiceServer will
// result in compilation errors.
type UnsafeAppendServiceServer interface {
	mustEmbedUnimplementedAppendServiceServer()
}

func RegisterAppendServiceServer(s grpc.ServiceRegistrar, srv AppendServiceServer) {
	// If the following call pancis, it indicates UnimplementedAppendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppendService_ServiceDesc, srv)
}

func _AppendService_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppendServiceServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppendService_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppendServiceServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppendService_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppendServiceServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppendService_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppendServiceServer).Checkpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppendService_ListEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppendServiceServer).ListEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppendService_ListEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppendServiceServer).ListEntries(ctx, req.(*ListEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppendService_ServiceDesc is the grpc.ServiceDesc for AppendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentos.kernel.ingest.v1.AppendService",
	HandlerType: (*AppendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _AppendService_Append_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _AppendService_Checkpoint_Handler,
		},
		{
			MethodName: "ListEntries",
			Handler:    _AppendService_ListEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ingest.proto",
}
