/**
 * ClarifyLoop — the clarify-or-fail-closed invariant (design §1 invariant 1) as a deterministic FSM.
 *
 * When `receiveText` (S1) cannot yet resolve a StructuredIntent because a required field is absent,
 * the zero-skill user is asked ONE templated question per missing field, in the order S1 reports
 * them. Answers are merged back into the text and re-parsed. The loop is HARD-CAPPED at
 * `CLARIFY_MAX_QUESTIONS` (= 3): if it is still ambiguous after 3 questions it DENIES — it never
 * guesses an intent. Ambiguity ⇒ deny (fail-closed).
 *
 * Determinism (design §5, capability gate G1 inactive): questions are templated from the missing
 * field name, NOT generated by an LLM, so RED tests are reproducible and the deny path is stable.
 *
 * Low coupling (design §2.2): a pure state machine over the same `personal/intent` module. It
 * consumes only S1's public `receiveText`; the entry redactor is injected (defaults to S1's, which
 * itself defaults to the audit barrel's `redactSecrets`). The carried continuation state (accumulated
 * text, caller identity, redactor) lives on a non-enumerable symbol key so it never appears in the
 * spec's public `ClarifyStep` shape, JSON serialization, or any audited projection.
 */
import { redactSecrets } from "../../audit/index.js";
import type { AgentContext } from "../../iam/ids.js";
import { type ReceiveDeps, receiveText } from "./gateway.js";
import type { StructuredIntent } from "./schema.js";

/** Hard cap on clarifying questions. Crossing it ⇒ fail-closed deny, never a guess. */
export const CLARIFY_MAX_QUESTIONS = 3;

export type ClarifyStep =
  | { status: "asking"; question: string; missing: string; asked: number }
  | { status: "resolved"; intent: StructuredIntent }
  | { status: "denied"; reason: string };

/** Continuation state, hidden from the public shape so it cannot leak into JSON / audit. */
const CONT = Symbol("clarify-continuation");
interface Continuation {
  text: string;
  ctx: AgentContext;
  deps: ReceiveDeps;
}
type AskingStep = ClarifyStep & { status: "asking"; [CONT]?: Continuation };

// Templated, deterministic question per missing field. Unknown fields get a safe generic prompt
// (still deny-by-default downstream — an unanswered field never resolves).
const QUESTION_TEMPLATES: Record<string, string> = {
  targets: "What should I act on?",
};
function questionFor(missing: string): string {
  return QUESTION_TEMPLATES[missing] ?? `Please specify "${missing}".`;
}

function ask(missing: string, asked: number, cont: Continuation): AskingStep {
  const step: AskingStep = {
    status: "asking",
    question: questionFor(missing),
    missing,
    asked,
  };
  // Non-enumerable so JSON.stringify / Object spreads never surface the continuation.
  Object.defineProperty(step, CONT, { value: cont, enumerable: false });
  return step;
}

/** Evaluate the accumulated text; either resolve, ask the next missing field, or deny. */
function evaluate(text: string, ctx: AgentContext, deps: ReceiveDeps, asked: number): ClarifyStep {
  const out = receiveText(text, ctx, deps);
  if (out.status === "intent") {
    return { status: "resolved", intent: out.intent };
  }
  if (out.status === "denied") {
    return { status: "denied", reason: out.reason };
  }
  // needs-clarification: ask the first still-missing field, if budget remains.
  if (asked >= CLARIFY_MAX_QUESTIONS) {
    return { status: "denied", reason: "clarification budget exhausted" };
  }
  const missing = out.missing[0] ?? "targets";
  return ask(missing, asked + 1, { text, ctx, deps });
}

/**
 * Begin a clarify session. If the text already resolves it returns `resolved`; if the gateway denies
 * it (unknown verb, bad identity, empty) it returns `denied` and never asks; otherwise it asks the
 * first missing field (`asked = 1`).
 */
export function startClarify(text: string, ctx: AgentContext, deps: ReceiveDeps = {}): ClarifyStep {
  return evaluate(text, ctx, deps, 0);
}

/**
 * Supply the user's answer to the current question. The answer is redacted (via the same injected
 * redactor) and merged into the accumulated text, then re-evaluated. Calling this on a `resolved` or
 * `denied` step is an inert no-op that returns the step unchanged — the hard cap cannot be bypassed
 * by re-invoking past a terminal state.
 */
export function answerClarify(
  state: ClarifyStep & { status: "asking" },
  answer: string,
): ClarifyStep {
  if (state.status !== "asking") {
    return state;
  }
  const cont = (state as AskingStep)[CONT];
  if (cont === undefined) {
    // Defensive fail-closed: an asking step without its continuation cannot be advanced.
    return { status: "denied", reason: "clarification state is not resumable" };
  }
  // Redact the answer with the same seam the gateway uses (injected → audit barrel default), so a
  // secret-shaped answer is scrubbed BEFORE it is merged into the accumulated text (design §3.3).
  const redact = cont.deps.redact ?? redactSecrets;
  const safeAnswer = redact(answer);
  const merged = `${cont.text} ${safeAnswer}`;
  return evaluate(merged, cont.ctx, cont.deps, state.asked);
}
