// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.28.1
// source: sidecar_adapter.subset.proto

/* eslint-disable */

export const protobufPackage = "spendguard.sidecar_adapter.v1";

/** common.proto:72 — UnitRef. */
export interface UnitRef {
  unitId: string;
  kind: UnitRef_Kind;
  currency: string;
  unitName: string;
  tokenKind: string;
  modelFamily: string;
  creditProgram: string;
}

export enum UnitRef_Kind {
  KIND_UNSPECIFIED = 0,
  MONETARY = 1,
  TOKEN = 2,
  CREDIT = 3,
  NON_MONETARY = 4,
  UNRECOGNIZED = -1,
}

/** common.proto:116 — PricingFreeze. */
export interface PricingFreeze {
  pricingVersion: string;
  priceSnapshotHash: Uint8Array;
  fxRateVersion: string;
  unitConversionVersion: string;
}

/** common.proto:200 — Error. */
export interface Error {
  code: Error_Code;
  message: string;
  details: { [key: string]: string };
}

export enum Error_Code {
  CODE_UNSPECIFIED = 0,
  FENCING_EPOCH_STALE = 1,
  LOCK_ORDER_TOKEN_MISMATCH = 2,
  PRICING_VERSION_UNKNOWN = 3,
  UNIT_NORMALIZATION_REQUIRED = 4,
  BUDGET_EXHAUSTED = 5,
  DEADLOCK_TIMEOUT = 6,
  SYNC_REPLICA_UNAVAILABLE = 7,
  TENANT_DISABLED = 8,
  SCHEMA_BUNDLE_UNKNOWN = 9,
  SIGNATURE_INVALID = 10,
  AUDIT_INVARIANT_VIOLATED = 11,
  DUPLICATE_DECISION_EVENT = 12,
  RESERVATION_STATE_CONFLICT = 13,
  PRICING_FREEZE_MISMATCH = 14,
  OVERRUN_RESERVATION = 15,
  RESERVATION_TTL_EXPIRED = 16,
  MULTI_RESERVATION_COMMIT_DEFERRED = 17,
  IDEMPOTENCY_CONFLICT = 18,
  UNRECOGNIZED = -1,
}

export interface Error_DetailsEntry {
  key: string;
  value: string;
}

export interface ReserveSessionRequest {
  tenantId: string;
  budgetId: string;
  windowInstanceId: string;
  unit: UnitRef | undefined;
  pricing: PricingFreeze | undefined;
  sessionId: string;
  route: string;
  estimatedAmountAtomic: string;
  ttlSeconds: number;
  idempotencyKey: string;
}

export interface ReserveSessionOutcome {
  outcome:
    | { $case: "accepted"; accepted: ReserveSessionAccepted }
    | { $case: "denied"; denied: ReserveSessionDenied }
    | { $case: "error"; error: Error }
    | undefined;
}

export interface ReserveSessionAccepted {
  sessionReservationId: string;
  ledgerTransactionId: string;
  auditSessionEventId: string;
  ttlExpiresAt: string | undefined;
  reservedAmountAtomic: string;
  remainingAmountAtomic: string;
}

export interface ReserveSessionDenied {
  auditSessionEventId: string;
  reasonCodes: string[];
  matchedRuleIds: string[];
  error: Error | undefined;
}

export interface CommitSessionDeltaRequest {
  sessionReservationId: string;
  streamingCommitId: string;
  amountAtomicDelta: string;
  outcome: CommitSessionDeltaRequest_Outcome;
  eventTime: string | undefined;
  idempotencyKey: string;
}

export enum CommitSessionDeltaRequest_Outcome {
  OUTCOME_UNSPECIFIED = 0,
  SUCCESS = 1,
  PROVIDER_ERROR = 2,
  CLIENT_TIMEOUT = 3,
  RUN_ABORTED = 4,
  UNRECOGNIZED = -1,
}

export interface CommitSessionDeltaOutcome {
  outcome: { $case: "accepted"; accepted: CommitSessionDeltaAccepted } | { $case: "error"; error: Error } | undefined;
}

export interface CommitSessionDeltaAccepted {
  sessionReservationId: string;
  streamingCommitId: string;
  ledgerTransactionId: string;
  auditSessionEventId: string;
  committedDeltaAtomic: string;
  cumulativeCommittedAtomic: string;
  remainingAmountAtomic: string;
  recordedAt: string | undefined;
}

export interface ReleaseSessionRequest {
  sessionReservationId: string;
  reasonCode: string;
  eventTime: string | undefined;
  idempotencyKey: string;
}

export interface ReleaseSessionOutcome {
  outcome: { $case: "accepted"; accepted: ReleaseSessionAccepted } | { $case: "error"; error: Error } | undefined;
}

export interface ReleaseSessionAccepted {
  sessionReservationId: string;
  ledgerTransactionId: string;
  auditSessionEventId: string;
  releasedAmountAtomic: string;
  committedAmountAtomic: string;
  recordedAt: string | undefined;
}

export interface ReleaseReservationRequest {
  reservationId: string;
  idempotencyKey: string;
  reasonCodes: string[];
  tenantId: string;
  workloadInstanceId: string;
  sessionId: string;
}

export interface ReleaseReservationResponse {
  auditEventSignature: Uint8Array;
  ledgerTransactionId: string;
  releasedReservationIds: string[];
}

export interface SidecarAdapter {
  /**
   * Reserve a session-scoped ledger hold before a realtime session connects to
   * paid model providers. Idempotent by
   * (tenant_id, session_id, route, idempotency_key). (adapter.proto:124)
   */
  ReserveSession(request: ReserveSessionRequest): Promise<ReserveSessionOutcome>;
  /**
   * Commit one positive streaming spend delta against an existing session
   * reservation. Idempotent by (session_reservation_id, streaming_commit_id).
   * amount_atomic_delta MUST be > 0. (adapter.proto:129)
   */
  CommitSessionDelta(request: CommitSessionDeltaRequest): Promise<CommitSessionDeltaOutcome>;
  /**
   * Release the uncommitted remainder of a session-scoped reservation.
   * Idempotent by (session_reservation_id, idempotency_key). (adapter.proto:134)
   */
  ReleaseSession(request: ReleaseSessionRequest): Promise<ReleaseSessionOutcome>;
  /**
   * Adapter-initiated release of a held reservation before commit.
   * Idempotent by (reservation_id, idempotency_key). (adapter.proto:116)
   */
  ReleaseReservation(request: ReleaseReservationRequest): Promise<ReleaseReservationResponse>;
}
