// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.28.1
// source: sidecar_adapter.subset.proto

/* eslint-disable */

export const protobufPackage = "spendguard.sidecar_adapter.v1";

/** common.proto:72 — UnitRef. */
export interface UnitRef {
  unitId: string;
  kind: UnitRef_Kind;
  currency: string;
  unitName: string;
  tokenKind: string;
  modelFamily: string;
  creditProgram: string;
}

export enum UnitRef_Kind {
  KIND_UNSPECIFIED = 0,
  MONETARY = 1,
  TOKEN = 2,
  CREDIT = 3,
  NON_MONETARY = 4,
  UNRECOGNIZED = -1,
}

/** common.proto:116 — PricingFreeze. */
export interface PricingFreeze {
  pricingVersion: string;
  priceSnapshotHash: Uint8Array;
  fxRateVersion: string;
  unitConversionVersion: string;
}

/** common.proto:200 — Error. */
export interface Error {
  code: Error_Code;
  message: string;
  details: { [key: string]: string };
}

export enum Error_Code {
  CODE_UNSPECIFIED = 0,
  FENCING_EPOCH_STALE = 1,
  LOCK_ORDER_TOKEN_MISMATCH = 2,
  PRICING_VERSION_UNKNOWN = 3,
  UNIT_NORMALIZATION_REQUIRED = 4,
  BUDGET_EXHAUSTED = 5,
  DEADLOCK_TIMEOUT = 6,
  SYNC_REPLICA_UNAVAILABLE = 7,
  TENANT_DISABLED = 8,
  SCHEMA_BUNDLE_UNKNOWN = 9,
  SIGNATURE_INVALID = 10,
  AUDIT_INVARIANT_VIOLATED = 11,
  DUPLICATE_DECISION_EVENT = 12,
  RESERVATION_STATE_CONFLICT = 13,
  PRICING_FREEZE_MISMATCH = 14,
  OVERRUN_RESERVATION = 15,
  RESERVATION_TTL_EXPIRED = 16,
  MULTI_RESERVATION_COMMIT_DEFERRED = 17,
  IDEMPOTENCY_CONFLICT = 18,
  UNRECOGNIZED = -1,
}

export interface Error_DetailsEntry {
  key: string;
  value: string;
}

/** common.proto:37 — TraceContext (W3C trace context; S8 RequestDecision.trace). */
export interface TraceContext {
  traceId: string;
  spanId: string;
  parentSpanId: string;
  traceState: string;
}

/** common.proto:51 — SpendGuardIds (canonical UUID v7 IDs; S8 RequestDecision.ids). */
export interface SpendGuardIds {
  runId: string;
  stepId: string;
  llmCallId: string;
  toolCallId: string;
  decisionId: string;
  snapshotId: string;
}

/** common.proto:232 — BudgetClaim (a single projected cost claim; S8 Inputs.projected_claims). */
export interface BudgetClaim {
  budgetId: string;
  unit: UnitRef | undefined;
  amountAtomic: string;
  direction: BudgetClaim_Direction;
  windowInstanceId: string;
}

export enum BudgetClaim_Direction {
  DIRECTION_UNSPECIFIED = 0,
  DEBIT = 1,
  CREDIT = 2,
  UNRECOGNIZED = -1,
}

export interface ReserveSessionRequest {
  tenantId: string;
  budgetId: string;
  windowInstanceId: string;
  unit: UnitRef | undefined;
  pricing: PricingFreeze | undefined;
  sessionId: string;
  route: string;
  estimatedAmountAtomic: string;
  ttlSeconds: number;
  idempotencyKey: string;
}

export interface ReserveSessionOutcome {
  outcome:
    | { $case: "accepted"; accepted: ReserveSessionAccepted }
    | { $case: "denied"; denied: ReserveSessionDenied }
    | { $case: "error"; error: Error }
    | undefined;
}

export interface ReserveSessionAccepted {
  sessionReservationId: string;
  ledgerTransactionId: string;
  auditSessionEventId: string;
  ttlExpiresAt: string | undefined;
  reservedAmountAtomic: string;
  remainingAmountAtomic: string;
}

export interface ReserveSessionDenied {
  auditSessionEventId: string;
  reasonCodes: string[];
  matchedRuleIds: string[];
  error: Error | undefined;
}

export interface CommitSessionDeltaRequest {
  sessionReservationId: string;
  streamingCommitId: string;
  amountAtomicDelta: string;
  outcome: CommitSessionDeltaRequest_Outcome;
  eventTime: string | undefined;
  idempotencyKey: string;
}

export enum CommitSessionDeltaRequest_Outcome {
  OUTCOME_UNSPECIFIED = 0,
  SUCCESS = 1,
  PROVIDER_ERROR = 2,
  CLIENT_TIMEOUT = 3,
  RUN_ABORTED = 4,
  UNRECOGNIZED = -1,
}

export interface CommitSessionDeltaOutcome {
  outcome: { $case: "accepted"; accepted: CommitSessionDeltaAccepted } | { $case: "error"; error: Error } | undefined;
}

export interface CommitSessionDeltaAccepted {
  sessionReservationId: string;
  streamingCommitId: string;
  ledgerTransactionId: string;
  auditSessionEventId: string;
  committedDeltaAtomic: string;
  cumulativeCommittedAtomic: string;
  remainingAmountAtomic: string;
  recordedAt: string | undefined;
}

export interface ReleaseSessionRequest {
  sessionReservationId: string;
  reasonCode: string;
  eventTime: string | undefined;
  idempotencyKey: string;
}

export interface ReleaseSessionOutcome {
  outcome: { $case: "accepted"; accepted: ReleaseSessionAccepted } | { $case: "error"; error: Error } | undefined;
}

export interface ReleaseSessionAccepted {
  sessionReservationId: string;
  ledgerTransactionId: string;
  auditSessionEventId: string;
  releasedAmountAtomic: string;
  committedAmountAtomic: string;
  recordedAt: string | undefined;
}

export interface ReleaseReservationRequest {
  reservationId: string;
  idempotencyKey: string;
  reasonCodes: string[];
  tenantId: string;
  workloadInstanceId: string;
  sessionId: string;
}

export interface ReleaseReservationResponse {
  auditEventSignature: Uint8Array;
  ledgerTransactionId: string;
  releasedReservationIds: string[];
}

/** adapter.proto:190 — HandshakeRequest (we send a minimal mandatory handshake). */
export interface HandshakeRequest {
  sdkVersion: string;
  runtimeKind: string;
  runtimeVersion: string;
  tenantIdAssertion: string;
  protocolVersion: number;
}

/** adapter.proto:211 — HandshakeResponse (we read back the negotiated session_id). */
export interface HandshakeResponse {
  sidecarVersion: string;
  protocolVersion: number;
  sessionId: string;
}

/**
 * adapter.proto:309 — DecisionRequest (we send session_id, trigger, route, cost
 * projection in Inputs; trace / ids carried opaque). Idempotency / prediction /
 * subscription-meter fields are OMITTED (the credential-blind transport sends none).
 */
export interface DecisionRequest {
  sessionId: string;
  trigger: DecisionRequest_Trigger;
  trace: TraceContext | undefined;
  ids: SpendGuardIds | undefined;
  route: string;
  inputs: DecisionRequest_Inputs | undefined;
}

export enum DecisionRequest_Trigger {
  TRIGGER_UNSPECIFIED = 0,
  RUN_PRE = 1,
  AGENT_STEP_PRE = 2,
  LLM_CALL_PRE = 3,
  TOOL_CALL_PRE = 4,
  UNRECOGNIZED = -1,
}

export interface DecisionRequest_Inputs {
  projectedClaims: BudgetClaim[];
  projectedP50Atomic: string;
  projectedP90Atomic: string;
  projectedP95Atomic: string;
  projectedP99Atomic: string;
  projectedUnit: UnitRef | undefined;
}

/**
 * adapter.proto:422 — DecisionResponse (we read decision_id + the decision enum;
 * unknown enum MUST fail closed per adapter.proto:448).
 */
export interface DecisionResponse {
  decisionId: string;
  auditDecisionEventId: string;
  decision: DecisionResponse_Decision;
  reasonCodes: string[];
  terminal: boolean;
  error: Error | undefined;
}

export enum DecisionResponse_Decision {
  DECISION_UNSPECIFIED = 0,
  CONTINUE = 1,
  DEGRADE = 2,
  SKIP = 3,
  STOP = 4,
  REQUIRE_APPROVAL = 5,
  STOP_RUN_PROJECTION = 6,
  UNRECOGNIZED = -1,
}

/** adapter.proto:516 — PublishOutcomeRequest (commit confirms a decision settled). */
export interface PublishOutcomeRequest {
  sessionId: string;
  decisionId: string;
  effectHash: Uint8Array;
  outcome: PublishOutcomeRequest_Outcome;
  adapterError: string;
}

export enum PublishOutcomeRequest_Outcome {
  OUTCOME_UNSPECIFIED = 0,
  APPLIED = 1,
  APPLIED_NOOP = 2,
  APPLY_FAILED = 3,
  APPROVAL_GRANTED = 4,
  APPROVAL_DENIED = 5,
  APPROVAL_TIMED_OUT = 6,
  UNRECOGNIZED = -1,
}

/** adapter.proto:535 — PublishOutcomeResponse (a populated error => fail closed). */
export interface PublishOutcomeResponse {
  auditOutcomeEventId: string;
  recordedAt: string | undefined;
  error: Error | undefined;
}

export interface SidecarAdapter {
  /**
   * (S8) Initial handshake; mandatory before any other RPC. The transport reads
   * back the negotiated session_id. (adapter.proto:39)
   */
  Handshake(request: HandshakeRequest): Promise<HandshakeResponse>;
  /**
   * (S8) Adapter requests a decision at a *.pre trigger point. The IMPLEMENTED
   * gating flow in the demo sidecar (adapter_uds.rs:82). (adapter.proto:46)
   */
  RequestDecision(request: DecisionRequest): Promise<DecisionResponse>;
  /**
   * (S8) Adapter confirms the publish_effect outcome (settles a decision).
   * (adapter.proto:50)
   */
  ConfirmPublishOutcome(request: PublishOutcomeRequest): Promise<PublishOutcomeResponse>;
  /**
   * Reserve a session-scoped ledger hold before a realtime session connects to
   * paid model providers. Idempotent by
   * (tenant_id, session_id, route, idempotency_key). (adapter.proto:124)
   */
  ReserveSession(request: ReserveSessionRequest): Promise<ReserveSessionOutcome>;
  /**
   * Commit one positive streaming spend delta against an existing session
   * reservation. Idempotent by (session_reservation_id, streaming_commit_id).
   * amount_atomic_delta MUST be > 0. (adapter.proto:129)
   */
  CommitSessionDelta(request: CommitSessionDeltaRequest): Promise<CommitSessionDeltaOutcome>;
  /**
   * Release the uncommitted remainder of a session-scoped reservation.
   * Idempotent by (session_reservation_id, idempotency_key). (adapter.proto:134)
   */
  ReleaseSession(request: ReleaseSessionRequest): Promise<ReleaseSessionOutcome>;
  /**
   * Adapter-initiated release of a held reservation before commit.
   * Idempotent by (reservation_id, idempotency_key). (adapter.proto:116)
   */
  ReleaseReservation(request: ReleaseReservationRequest): Promise<ReleaseReservationResponse>;
}
