// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.28.1
// source: ingest.proto

/* eslint-disable */

export const protobufPackage = "agentos.kernel.ingest.v1";

export interface AppendRequest {
  /** per-source monotonic sequence key (P3 binds tenant identity) */
  sourceId: string;
  /** the expected next sequence for this source (kernel enforces monotonic) */
  sequence: number;
  /** ALREADY-redacted S0.2 canonical bytes (kernel never holds the raw secret) */
  canonicalEvent: Uint8Array;
}

/** Receipt — the server computes prev_hash/entry_hash/content_hash; the client cannot set them. */
export interface Receipt {
  sequence: number;
  /** "sha256:"-prefixed (versioned prefix; not hardcoded to sha256 forever) */
  contentHash: string;
  /** "sha256:"-prefixed */
  prevHash: string;
  /** "sha256:"-prefixed */
  entryHash: string;
}

export interface AppendError {
  code: AppendError_Code;
  /** static reason / field name only — never echoes canonical_event content */
  detail: string;
}

export enum AppendError_Code {
  /** CODE_UNSPECIFIED - proto3 zero value -> treated as deny (fail-closed), never success */
  CODE_UNSPECIFIED = 0,
  /** SEQUENCE_GAP - sequence > next: gap detected */
  SEQUENCE_GAP = 1,
  /** SEQUENCE_REPLAY - sequence < next: position already settled -> rewrite refused (append-only) */
  SEQUENCE_REPLAY = 2,
  /** MALFORMED - canonical_event not parseable / not canonical */
  MALFORMED = 3,
  UNRECOGNIZED = -1,
}

export interface AppendResponse {
  result: { $case: "receipt"; receipt: Receipt } | { $case: "error"; error: AppendError } | undefined;
}

/**
 * AppendService is the kernel's ingest surface. It is APPEND-ONLY by construction: exactly one RPC
 * (Append) and no Update/Delete/Rewrite/Upsert/Overwrite — the control plane can only append, never
 * rewrite history (HARD CONSTRAINT; gating c1/c4). The server additionally enforces monotonic
 * per-source sequence and fails closed (typed AppendError + audit) on replay/gap/malformed.
 */
export interface AppendService {
  Append(request: AppendRequest): Promise<AppendResponse>;
}
