// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v5.28.1
// source: ingest.proto

/* eslint-disable */

export const protobufPackage = "agentos.kernel.ingest.v1";

export interface AppendRequest {
  /** per-source monotonic sequence key (P3 binds tenant identity) */
  sourceId: string;
  /** the expected next sequence for this source (kernel enforces monotonic) */
  sequence: number;
  /** ALREADY-redacted S0.2 canonical bytes (kernel never holds the raw secret) */
  canonicalEvent: Uint8Array;
  /** P3 tenant partition routing; empty => single-chain servers ignore it, the partitioned server fail-closed denies */
  partitionId: string;
}

/** Receipt — the server computes prev_hash/entry_hash/content_hash; the client cannot set them. */
export interface Receipt {
  sequence: number;
  /** "sha256:"-prefixed (versioned prefix; not hardcoded to sha256 forever) */
  contentHash: string;
  /** "sha256:"-prefixed */
  prevHash: string;
  /** "sha256:"-prefixed */
  entryHash: string;
}

export interface AppendError {
  code: AppendError_Code;
  /** static reason / field name only — never echoes canonical_event content */
  detail: string;
}

export enum AppendError_Code {
  /** CODE_UNSPECIFIED - proto3 zero value -> treated as deny (fail-closed), never success */
  CODE_UNSPECIFIED = 0,
  /** SEQUENCE_GAP - sequence > next: gap detected */
  SEQUENCE_GAP = 1,
  /** SEQUENCE_REPLAY - sequence < next: position already settled -> rewrite refused (append-only) */
  SEQUENCE_REPLAY = 2,
  /** MALFORMED - canonical_event not parseable / not canonical */
  MALFORMED = 3,
  UNRECOGNIZED = -1,
}

export interface AppendResponse {
  result: { $case: "receipt"; receipt: Receipt } | { $case: "error"; error: AppendError } | undefined;
}

/**
 * CheckpointRequest carries no fields: the anchor is the kernel's single global chain head; there is
 * no per-task / per-tenant scoping at the kernel (the WORM log is shared, monotonic, single-writer).
 */
export interface CheckpointRequest {
}

/** CheckpointResponse — the snapshot-safe anchor captured atomically under the append mutex. */
export interface CheckpointResponse {
  /** current chain head entryHash ("sha256:"-prefixed); genesis if empty log */
  headEntryHash: string;
  /** sequence of the head record (0 for an empty log; check per_source_next_seq for emptiness) */
  headSequence: number;
  /** expected next sequence per source (empty map => no appends yet) */
  perSourceNextSeq: { [key: string]: number };
  /**
   * checkpoint_signature is the kernel's base64 Ed25519 signature over CheckpointBytes(head_entry_hash,
   * length) — length being the chain's total entry COUNT (NOT head_sequence, which is a per-source
   * sequence). It lets a third party verify the operator's ACTUAL kernel chain head with chain.
   * VerifyCheckpoint / the released verifier. The kernel (attester process) signs; the control plane
   * (actor) can only Append and holds no key — attester != actor holds TO THE PROCESS BOUNDARY. The
   * signing key being operator-held (in-memory generated or loaded from a file) is the honest known
   * limit: real key externalization (HSM/KMS/remote attestation) is P4, NOT solved here.
   */
  checkpointSignature: string;
  /**
   * public_key is the kernel's Ed25519 public key in SPKI/PKIX DER (x509.MarshalPKIXPublicKey). A
   * verifier parses it with x509.ParsePKIXPublicKey -> ed25519.PublicKey to check checkpoint_signature.
   */
  publicKey: Uint8Array;
}

export interface CheckpointResponse_PerSourceNextSeqEntry {
  key: string;
  value: number;
}

/**
 * Entry is one read-back WORM record, field-aligned with chain.LogEntry (verifier-compatible). The
 * server re-derives canonical_event from the stored (already-redacted) event via the SAME canonical
 * function the chain used to seal it, so EntryHashFromCanonical(canonical_event, prev_hash, sequence)
 * reproduces entry_hash byte-for-byte. The client cannot set these — they are read from the durable log.
 */
export interface Entry {
  sequence: number;
  /** ALREADY-redacted canonical bytes (re-derived; byte-identical to what was hashed) */
  canonicalEvent: Uint8Array;
  /** "sha256:"-prefixed */
  prevHash: string;
  /** "sha256:"-prefixed */
  entryHash: string;
}

/** ListEntriesRequest selects the chain tail: entries with sequence >= from_sequence (0 => the whole log). */
export interface ListEntriesRequest {
  fromSequence: number;
}

/**
 * ListEntriesResponse carries the consistent snapshot of entries in chain order (never a partial slice;
 * a durable read failure surfaces as an Internal error instead).
 */
export interface ListEntriesResponse {
  entries: Entry[];
}

/**
 * AppendService is the kernel's ingest surface. It is APPEND-ONLY by construction: exactly one RPC
 * (Append) and no Update/Delete/Rewrite/Upsert/Overwrite — the control plane can only append, never
 * rewrite history (HARD CONSTRAINT; gating c1/c4). The server additionally enforces monotonic
 * per-source sequence and fails closed (typed AppendError + audit) on replay/gap/malformed.
 */
export interface AppendService {
  Append(request: AppendRequest): Promise<AppendResponse>;
  /**
   * Checkpoint is READ-ONLY: under the same append mutex it atomically captures a consistent snapshot
   * anchor {head_entry_hash, head_sequence, per_source_next_seq}. It NEVER appends, rewrites, or
   * truncates — it is a consistent read of the chain head + per-source next sequence so a snapshot
   * cannot observe a torn (half-written) tail. It does NOT widen the append-only surface.
   */
  Checkpoint(request: CheckpointRequest): Promise<CheckpointResponse>;
  /**
   * ListEntries is READ-ONLY: under the same append mutex it captures a consistent snapshot of the
   * durable WORM chain (store.Load), filters to sequence >= from_sequence, and returns the entries so a
   * client can re-derive entryHash and verify chain integrity (reading != attesting). It NEVER appends,
   * rewrites, or truncates, and on a durable read failure returns Internal — never a partial slice. It
   * does NOT widen the append-only surface.
   */
  ListEntries(request: ListEntriesRequest): Promise<ListEntriesResponse>;
}
